### ISSUE TITLE
Spark is uninstallable from MELPA

### ISSUE THREAD

**Issue by dakrone** [alvinfrancis/spark#1]
First, this looks like a great library and I'm excited to use it! (trying to build a monitoring dashboard), however, I'm unable to install it from MELPA because `cl-format` is a package only available on Marmalade.

Do you happen to know the cl-format author and would be able to get him/her to publish it also on MELPA?

**Comment by alvinfrancis** [comment]
Thanks for pointing this out.  The `cl-format` author is @politza, however I cannot find the associated repository in his profile. I'll try emailing him to see if he can publish his library to MELPA. In the meantime, I'll find time to rewrite the parts that require `cl-format` and see if I can drop that dependency. I might also look into just publishing `cl-format` to MELPA myself since it's also under the GNU Public License.

**Comment by politza** [comment]
Alvin Francis Dumalus <notifications@github.com> writes:

> I might also look into just publishing cl-format to MELPA myself since it's also under the GNU Public License.

I have no problem with that.  It's been a while since I've looked at it.

**Comment by alvinfrancis** [comment]
Hey, thanks for the awesome library. The built-in `format` in emacs is quite lacking. Anyway, I can publish the current `cl-format` to MELPA, but can I trouble you for a repository for it if it exists? It would be better to keep the version history for the project if possible.

**Comment by alvinfrancis** [comment]
I've currently dropped the dependency on `cl-format`.  Once 'cl-format` is published to MELPA, I might bring it back to the way it was.

**Comment by politza** [comment]
Alvin Francis Dumalus <notifications@github.com> writes:

> [...] but can I trouble you for a repository for it if it exists? It
> would be better to keep the version history for the project if
> possible.

It's in some svn repository, though I doubt that it contains a
meaningful history.  I suggest you just start a new one.

**Comment by alvinfrancis** [comment]
> It's in some svn repository, though I doubt that it contains a
meaningful history.  I suggest you just start a new one.

Okay. I will do that. Thanks for your time.

**Comment by dakrone** [comment]
Thanks for fixing this @alvinfrancis :) I'm going to close this for now
