### ISSUE TITLE
Improvement suggestion: add SVG sparklines

### ISSUE THREAD

**Issue by tzz** [alvinfrancis/spark#2]
I have code that I use to generate SVG representations of individual numbers (for Gnus read/unread counts). It works great in Emacs compiled with the right libraries. It wouldn't be hard to bring my code into this library and extend it to also support the classic sparklines. Are you interested?

I don't want to create a new pull request if you feel this is beyond the scope of your library, but I think SVG graphics will look much nicer while still being easily embeddable inside Emacs buffers.

**Comment by alvinfrancis** [comment]
Unfortunately, I feel like that would be beyond what I want the library to be for; purely textual visualisation. That still sounds like a pretty cool library though and I suggest you publishing it as a separate library if ever. Thanks anyway!
